apiVersion: v1
kind: Service
metadata:
  name: front-node-port  # Name of the Service object

spec:
  type: NodePort  # Expose the Service on a port on each node
  ports:
    - port: 80  # Port exposed externally by the Service
      targetPort: 80  # Port on the pods to forward traffic to
      nodePort: 31515  # Port on each node to expose the Service

  selector:
    component: front  # Select pods with the label "component: front" to target
